plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/jonieldasilva/Local/Claude/JDS"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/work/they-fight-with-cameras"
to = "/work/they-fight-with-cameras.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/work/radiologie-ahrensburg"
to = "/work/radiologie-ahrensburg.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/work/lm-alltagshilfe"
to = "/work/lm-alltagshilfe.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/work/steent"
to = "/work/steent.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/work/decarbonaid"
to = "/work/decarbonaid.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/work/blablador"
to = "/work/blablador.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]